### ISSUE TITLE
Log debug messages to a file in addition to the console

### ISSUE THREAD

**Issue by davemfish** [natcap/invest-gui#25]
There are `console.log` calls throughout the source which will continue to be useful for debugging. But we should also log those messages to a file so that when the app is in production, we can have users submit bug reports with that log.

More broadly, manage logging so it is useful for bug reports.

**Comment by phargogh** [comment]
Oh man, this would be so so useful for debugging application crashes.  PLUS it'd eliminate the strict need for the console window to be presented in a Windows build.
